//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.Employee_Course = new HashSet<Employee_Course>();
        }
    
        public int ID_CURSO { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<int> DURACION { get; set; }
        public Nullable<int> CALIFICACION_MIN { get; set; }
        public string TIPO_CURSO { get; set; }
        public string CLASIFICACION { get; set; }
        public string AREA_TEMATICA { get; set; }
        public string AREA_APLICACION { get; set; }
        public string OBJETIVO { get; set; }
        public string MODALIDAD { get; set; }
        public string COMENTARIOS { get; set; }
        public Nullable<int> ID_INSTRUCTOR { get; set; }
    
        public virtual Instructor Instructor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Course> Employee_Course { get; set; }
    }
}
