//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Employee_Course = new HashSet<Employee_Course>();
        }
    
        public int ID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string FullLegalName { get; set; }
        public string LegalNameLastName { get; set; }
        public string LegalNameSecondaryLastName { get; set; }
        public string LegalNameFirstName { get; set; }
        public string JobCode { get; set; }
        public string JobProfile { get; set; }
        public string JobTitle { get; set; }
        public Nullable<int> SupervisoryOrganizationID { get; set; }
        public string SupervisoryOrganization { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public string ManagerName { get; set; }
        public Nullable<int> LocationCode { get; set; }
        public string Location { get; set; }
        public string HireDate { get; set; }
        public Nullable<double> JCICFBasePayDaily { get; set; }
        public string MexicoRFC { get; set; }
        public string MexicoCURP { get; set; }
        public string MexicoIMSS { get; set; }
        public string JobCategory { get; set; }
        public string WorkShift { get; set; }
        public string ShiftMexico { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Course> Employee_Course { get; set; }
    }
}
