CREATE DATABASE RecursosHumanos
GO
USE RecursosHumanos
GO

CREATE TABLE Instructor(
	ID_INSTRUCTOR INT PRIMARY KEY IDENTITY(1,1),
	NOMBRE_COMPLETO VARCHAR (300),
	TIPO VARCHAR(30),
	COMPANIA VARCHAR(60),
	REGISTRO_STP VARCHAR(300)
)

CREATE TABLE Employee(
	ID INT PRIMARY KEY IDENTITY(1,1),
	EmployeeID INT,
	FullLegalName VARCHAR(100),
	LegalNameLastName VARCHAR(30),
	LegalNameSecondaryLastName VARCHAR(30),
	LegalNameFirstName VARCHAR(30),
	JobCode VARCHAR(30),
	JobProfile VARCHAR(50),
	JobTitle VARCHAR(50),
	SupervisoryOrganizationID INT,
	SupervisoryOrganization VARCHAR(100),
	ManagerID INT,
	ManagerName VARCHAR(100),
	LocationCode INT,
	Location VARCHAR(100),
	HireDate VARCHAR(100),
	JCICFBasePayDaily FLOAT,
	MexicoRFC VARCHAR(13),
	MexicoCURP VARCHAR(18),
	MexicoIMSS VARCHAR(11),
	JobCategory VARCHAR(50),
	WorkShift VARCHAR(100),
	ShiftMexico VARCHAR(30)
)

CREATE TABLE Course (
	ID_CURSO INT PRIMARY KEY IDENTITY(1,1),
	NOMBRE VARCHAR(60),
	DURACION INT,
	CALIFICACION_MIN INT,
	TIPO_CURSO VARCHAR(30),
	CLASIFICACION VARCHAR(300),
	AREA_TEMATICA VARCHAR(300),
	AREA_APLICACION VARCHAR(60),
	OBJETIVO VARCHAR(300),
	MODALIDAD VARCHAR(30),
	COMENTARIOS VARCHAR(600),
	ID_INSTRUCTOR INT,
	FOREIGN KEY (ID_INSTRUCTOR) REFERENCES Instructor(ID_INSTRUCTOR),
)

CREATE TABLE Employee_Course(
	ID_EMPLEADO_CURSO INT PRIMARY KEY IDENTITY(1,1),
	ID_EMPLEADO INT,
	ID_CURSO INT,
	FECHA DATETIME DEFAULT GETDATE(),
	CALIFICACION INT,
	FOREIGN KEY (ID_EMPLEADO) REFERENCES Employee(ID),
	FOREIGN KEY (ID_CURSO) REFERENCES Course(ID_CURSO)
)